export const GET_ERRORS = "GET_ERRORS";
export const GET_ATTENDANCES = "GET_ATTENDANCES";
export const UPDATE_ATTENDANCE="UPDATE_ATTENDANCE";
export const GET_EMPERRORS = "GET_EMPERRORS";
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_EMPLOYEE="GET_EMPLOYEE";
export const GET_ATTENDANCE = "GET_ATTENDANCE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
